// AUTO-GENERATED by scripts/generate-config-registry.mjs -- DO NOT EDIT
import type { AccountConfig, AgentConfig, ContentConfig } from "./types";

export const accounts: Record<string, AccountConfig> = {
  "jenise-buckalew": {
    "handle": "jenise-buckalew",
    "template": "emerald-classic",
    "branding": {
      "primary_color": "#1B5E20",
      "secondary_color": "#2E7D32",
      "accent_color": "#C8A951",
      "font_family": "Segoe UI",
      "logo_url": "/agents/jenise-buckalew/logo.png"
    },
    "brokerage": {
      "name": "Green Light Realty LLC",
      "license_number": "1751390",
      "office_phone": "(732) 251-2500 ext 714",
      "office_address": "1109 Englishtown Rd, Old Bridge, NJ 08857"
    },
    "agent": {
      "enabled": true,
      "id": "jenise-buckalew",
      "name": "Jenise Buckalew",
      "title": "REALTOR®",
      "phone": "(347) 393-5993",
      "email": "jenisesellsnj@gmail.com",
      "headshot_url": "/agents/jenise-buckalew/headshot.jpg",
      "license_number": "0676823",
      "languages": [
        "English",
        "Spanish"
      ],
      "tagline": "Forward. Moving."
    },
    "location": {
      "state": "NJ",
      "service_areas": [
        "Middlesex County",
        "Monmouth County",
        "Ocean County"
      ]
    },
    "integrations": {
      "email_provider": "gmail"
    },
    "compliance": {
      "state_form": "NJ-REALTORS-118",
      "licensing_body": "NJ Real Estate Commission",
      "disclosure_requirements": [
        "Lead-based paint disclosure (pre-1978)",
        "Seller property condition disclosure"
      ]
    },
    "contact_info": [
      {
        "type": "email",
        "value": "jenisesellsnj@gmail.com",
        "label": "Personal Email",
        "is_preferred": false
      },
      {
        "type": "phone",
        "value": "(347) 393-5993",
        "label": "Cell Phone",
        "is_preferred": true
      },
      {
        "type": "phone",
        "value": "(732) 251-2500",
        "ext": "714",
        "label": "Office Phone",
        "is_preferred": false
      }
    ]
  },
  "test-broker-agent": {
    "handle": "test-broker-agent",
    "template": "emerald-classic",
    "branding": {
      "primary_color": "#2c3e50",
      "accent_color": "#e67e22"
    },
    "brokerage": {
      "name": "Broker Direct Realty",
      "license_number": "NJ-2024-99999"
    },
    "agent": {
      "enabled": true,
      "id": "test-broker-agent",
      "name": "Diana Reyes",
      "title": "Broker/Owner",
      "phone": "(973) 555-0300",
      "email": "diana@brokerdirect.com",
      "tagline": "Broker and mentor."
    },
    "location": {
      "state": "NJ",
      "service_areas": [
        "Newark",
        "Montclair"
      ]
    }
  },
  "test-brokerage": {
    "handle": "test-brokerage",
    "template": "emerald-classic",
    "branding": {
      "primary_color": "#1a1a2e",
      "secondary_color": "#16213e",
      "accent_color": "#d4af37",
      "font_family": "Georgia"
    },
    "brokerage": {
      "name": "Sterling & Associates Real Estate",
      "license_number": "NJ-2024-12345",
      "office_address": "100 Summit Ave, Summit, NJ 07901",
      "office_phone": "(908) 555-0100"
    },
    "broker": {
      "name": "Victoria Sterling",
      "title": "Managing Broker",
      "bio": "30 years of luxury real estate experience."
    },
    "location": {
      "state": "NJ",
      "service_areas": [
        "Summit",
        "Short Hills",
        "Chatham"
      ]
    }
  },
  "test-emerald": {
    "handle": "test-emerald",
    "template": "emerald-classic",
    "branding": {
      "primary_color": "#1B5E20",
      "secondary_color": "#2E7D32",
      "accent_color": "#C8A951",
      "font_family": "Segoe UI",
      "logo_url": ""
    },
    "brokerage": {
      "name": "Evergreen Homes Realty",
      "license_number": "BR-44210",
      "office_phone": "(732) 555-0300 ext 110",
      "office_address": "250 Main St, Woodbridge, NJ 07095"
    },
    "agent": {
      "enabled": true,
      "id": "test-emerald",
      "name": "Patricia Collins",
      "title": "REALTOR®",
      "phone": "(732) 555-0303",
      "email": "patricia@evergreenhomes.com",
      "headshot_url": "/agents/test-emerald/headshot.jpg",
      "license_number": "9876543",
      "languages": [
        "English"
      ],
      "tagline": "Your Home. Your Future. My Priority."
    },
    "location": {
      "state": "NJ",
      "service_areas": [
        "Middlesex County",
        "Union County",
        "Somerset County"
      ]
    },
    "integrations": {
      "email_provider": "gmail"
    },
    "compliance": {
      "state_form": "NJ-REALTORS-118",
      "licensing_body": "NJ Real Estate Commission",
      "disclosure_requirements": [
        "Lead-based paint disclosure (pre-1978)",
        "Seller property condition disclosure"
      ]
    },
    "contact_info": [
      {
        "type": "phone",
        "value": "(732) 555-0303",
        "label": "Cell Phone",
        "is_preferred": true
      },
      {
        "type": "phone",
        "value": "(732) 555-0300",
        "ext": "110",
        "label": "Office Phone",
        "is_preferred": false
      },
      {
        "type": "email",
        "value": "patricia@evergreenhomes.com",
        "label": "Email",
        "is_preferred": false
      }
    ]
  },
  "test-modern": {
    "handle": "test-modern",
    "template": "modern-minimal",
    "branding": {
      "primary_color": "#1A237E",
      "secondary_color": "#283593",
      "accent_color": "#FF6F61",
      "font_family": "Inter",
      "logo_url": ""
    },
    "brokerage": {
      "name": "Metro Realty Group",
      "license_number": "MRG-NYC-2201",
      "office_phone": "(212) 555-0100",
      "office_address": "350 Fifth Ave, Suite 4100, New York, NY 10118"
    },
    "agent": {
      "enabled": true,
      "id": "test-modern",
      "name": "Alex Rivera",
      "title": "Licensed Real Estate Salesperson",
      "phone": "(212) 555-0101",
      "email": "alex@testrealty.com",
      "headshot_url": "/agents/test-modern/headshot.jpg",
      "license_number": "10401098765",
      "languages": [
        "English",
        "Portuguese"
      ],
      "tagline": "City Living. Simplified."
    },
    "location": {
      "state": "NY",
      "service_areas": [
        "Manhattan",
        "Brooklyn",
        "Queens",
        "Long Island City"
      ]
    },
    "integrations": {
      "email_provider": "gmail"
    },
    "compliance": {
      "state_form": "NY-DOS-1736",
      "licensing_body": "NY Department of State",
      "disclosure_requirements": [
        "Property condition disclosure (PCDS)",
        "Lead-based paint disclosure (pre-1978)"
      ]
    },
    "contact_info": [
      {
        "type": "phone",
        "value": "(212) 555-0101",
        "label": "Cell Phone",
        "is_preferred": true
      },
      {
        "type": "phone",
        "value": "(212) 555-0100",
        "label": "Office",
        "is_preferred": false
      },
      {
        "type": "email",
        "value": "alex@testrealty.com",
        "label": "Email",
        "is_preferred": false
      }
    ]
  },
  "test-warm": {
    "handle": "test-warm",
    "template": "warm-community",
    "branding": {
      "primary_color": "#5D1A1A",
      "secondary_color": "#7B2D2D",
      "accent_color": "#D4A843",
      "font_family": "Georgia",
      "logo_url": ""
    },
    "brokerage": {
      "name": "Hill Country Realty",
      "license_number": "HCR-ATX-1105",
      "office_phone": "(512) 555-0200 ext 15",
      "office_address": "1100 Congress Ave, Suite 200, Austin, TX 78701"
    },
    "agent": {
      "enabled": true,
      "id": "test-warm",
      "name": "Maria Santiago",
      "title": "REALTOR®",
      "phone": "(512) 555-0202",
      "email": "maria@hillcountryrealty.com",
      "headshot_url": "/agents/test-warm/headshot.jpg",
      "license_number": "TX-0654321",
      "languages": [
        "English",
        "Spanish"
      ],
      "tagline": "Your Neighbor. Your REALTOR®."
    },
    "location": {
      "state": "TX",
      "service_areas": [
        "Austin",
        "Round Rock",
        "Cedar Park",
        "Georgetown",
        "Pflugerville"
      ]
    },
    "integrations": {
      "email_provider": "gmail"
    },
    "compliance": {
      "state_form": "TREC-20-16",
      "licensing_body": "Texas Real Estate Commission",
      "disclosure_requirements": [
        "Seller's disclosure notice (TREC OP-H)",
        "Lead-based paint disclosure (pre-1978)",
        "MUD/PID disclosure"
      ]
    },
    "contact_info": [
      {
        "type": "phone",
        "value": "(512) 555-0202",
        "label": "Cell Phone",
        "is_preferred": true
      },
      {
        "type": "phone",
        "value": "(512) 555-0200",
        "ext": "15",
        "label": "Office Phone",
        "is_preferred": false
      },
      {
        "type": "email",
        "value": "maria@hillcountryrealty.com",
        "label": "Email",
        "is_preferred": false
      }
    ]
  }
} as unknown as Record<string, AccountConfig>;

export const accountContent: Record<string, ContentConfig> = {
  "jenise-buckalew": {
    "navigation": {
      "items": [
        {
          "label": "Why Choose Me",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "How It Works",
          "href": "#steps",
          "enabled": true
        },
        {
          "label": "Recent Sales",
          "href": "#gallery",
          "enabled": true
        },
        {
          "label": "Testimonials",
          "href": "#testimonials",
          "enabled": true
        },
        {
          "label": "Ready to Move?",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "About",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Buy or Sell with Confidence",
              "highlight_word": "Confidence",
              "tagline": "Forward. Moving.",
              "body": "I'm Jenise Buckalew, a NJ State Licensed REALTOR® and independent agent with Green Light Realty LLC. With over 100 homes sold across 20 years in the business, I deliver results — whether you're selling your home for top dollar or searching for the perfect place to call home. Selling? I'll start with a free, instant Comparative Market Analysis so you know exactly what your home is worth. Buying? Tell me what you're looking for and I'll find it.",
              "cta_text": "Get Your Free Home Value Report in Minutes",
              "cta_link": "#cma-form"
            }
          },
          "stats": {
            "enabled": true,
            "data": {
              "items": [
                {
                  "value": "100+",
                  "label": "Homes Sold"
                },
                {
                  "value": "5.0 ★",
                  "label": "Zillow Rating (24 Reviews)"
                },
                {
                  "value": "Gold",
                  "label": "NJ REALTORS® Circle of Excellence"
                },
                {
                  "value": "20+",
                  "label": "Years of Experience"
                },
                {
                  "value": "$500K–$1.5M",
                  "label": "Sale Price Range"
                }
              ]
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "What I Bring to the Table",
              "subtitle": "Every client gets the full package — no cutting corners.",
              "items": [
                {
                  "title": "Free Home Value Report in Minutes",
                  "description": "Submit your info and get a personalized Home Value Report within minutes — so you know exactly what your home is worth before we even meet."
                },
                {
                  "title": "Professional Photography",
                  "description": "Every listing gets high-quality, professionally shot photos that make buyers stop scrolling and start scheduling showings."
                },
                {
                  "title": "Strategic Pricing",
                  "description": "Data-driven pricing backed by real comparable sales in your neighborhood — priced to attract serious offers fast."
                },
                {
                  "title": "Home Prep Guidance",
                  "description": "I'll walk through your home and tell you exactly what small changes can boost your sale price — no expensive renovations needed."
                },
                {
                  "title": "Maximum Exposure",
                  "description": "Your home gets listed on the MLS, Zillow, Realtor.com, social media, and more — seen by thousands of active buyers."
                },
                {
                  "title": "Personalized Home Search",
                  "description": "Looking for a home? Tell me your must-haves — area, price range, bedrooms — and I'll send you listings that match, before they hit the public market."
                },
                {
                  "title": "Se Habla Español",
                  "description": "Bilingual service in English and Spanish so every client feels heard, understood, and confident throughout the process."
                }
              ]
            }
          },
          "steps": {
            "enabled": true,
            "data": {
              "title": "How It Works",
              "subtitle": "Three simple steps to get started.",
              "steps": [
                {
                  "number": 1,
                  "title": "Submit Your Info",
                  "description": "Fill out the quick form below with your property details. It takes less than 2 minutes."
                },
                {
                  "number": 2,
                  "title": "Get Your Free Home Value Report",
                  "description": "Selling your home? I'll send you a personalized Home Value Report within minutes showing what your home is worth based on recent comparable sales. Buying? I'll reach out to learn more about what you're looking for."
                },
                {
                  "number": 3,
                  "title": "Schedule a Walkthrough",
                  "description": "I'll visit your home in person to give you the most accurate price based on your upgrades and unique features."
                }
              ]
            }
          },
          "gallery": {
            "enabled": true,
            "data": {
              "title": "Recently Sold by Jenise",
              "subtitle": "Real results from the Zillow profile — verified sales.",
              "items": [
                {
                  "address": "308 Myrtle St",
                  "city": "Cliffwood",
                  "state": "NJ",
                  "price": "$660,000",
                  "image_url": "/agents/jenise-buckalew/sold/308-myrtle-st.jpg"
                },
                {
                  "address": "16 Hershey Rd",
                  "city": "East Brunswick",
                  "state": "NJ",
                  "price": "$650,000",
                  "image_url": "/agents/jenise-buckalew/sold/16-hershey-rd.jpg"
                },
                {
                  "address": "18 Charlotte St",
                  "city": "Sayreville",
                  "state": "NJ",
                  "price": "$640,000",
                  "image_url": "/agents/jenise-buckalew/sold/18-charlotte-st.jpg"
                },
                {
                  "address": "195 College Dr",
                  "city": "Edison",
                  "state": "NJ",
                  "price": "$260,000",
                  "image_url": "/agents/jenise-buckalew/sold/195-college-dr.jpg"
                }
              ]
            }
          },
          "testimonials": {
            "enabled": true,
            "data": {
              "title": "What My Clients Say",
              "subtitle": "Real reviews from real clients on Zillow.",
              "items": [
                {
                  "text": "Jenise was absolutely amazing throughout the entire process. She was always available, incredibly knowledgeable, and made everything so easy. I couldn't have asked for a better experience!",
                  "reviewer": "sra56",
                  "rating": 5,
                  "source": "Zillow"
                },
                {
                  "text": "Jenise is a fantastic realtor! She guided us through every step and was always patient with our questions. Her expertise made our home sale smooth and stress-free.",
                  "reviewer": "rv skaarup",
                  "rating": 5,
                  "source": "Zillow"
                },
                {
                  "text": "Working with Jenise was the best decision we made. She is professional, responsive, and truly cares about her clients. She sold our home fast and for a great price!",
                  "reviewer": "brittneyc12597",
                  "rating": 5,
                  "source": "Zillow"
                },
                {
                  "text": "Jenise went above and beyond for us. She was there every step of the way and made the whole process seamless. Highly recommend her to anyone buying or selling!",
                  "reviewer": "abbynormal56",
                  "rating": 5,
                  "source": "Zillow"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "Ready to Make a Move?",
              "subtitle": "Selling? Get your free Home Value Report in minutes.® Buying? Tell me what you're looking for.",
              "description": "Selling your home? Enter your address below to receive a free Market Analysis in minutes! Looking to buy? Tell me what you're looking for and I'll help you find it. **100% free, no obligation.**"
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "About Jenise",
              "bio": [
                "I'm Jenise Buckalew — a NJ State Licensed REALTOR®, proud mother of five, and an independent agent with Green Light Realty LLC. With over 20 years of experience and hundreds of successful transactions, I specialize in helping homeowners across Middlesex, Monmouth, and Ocean Counties get the best value for their biggest investment.",
                "I'm a recurring NJ REALTORS® Circle of Excellence award winner with a perfect 5.0 Zillow rating. I believe every client deserves hands-on, personalized service — from a free professional CMA to expert home prep advice and professional photography. Whether you're buying your first home or selling a property you've owned for decades, I bring the same dedication to every transaction.",
                "Green Light Realty LLC operates three offices — one in Ocean County and two in Middlesex County — giving my clients broad reach across Central New Jersey."
              ],
              "credentials": [
                "NJ State Licensed",
                "Circle of Excellence",
                "100+ Homes Sold",
                "5.0 ★ Zillow",
                "Se Habla Español"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "Your Free Home Value Report Is Being Prepared Now!",
        "body": "{firstName} will send your personalized Comparative Market Analysis to your email shortly. Keep an eye on your inbox!",
        "disclaimer": "This home value report is a Comparative Market Analysis (CMA) and is not an appraisal. It should not be considered the equivalent of an appraisal.",
        "cta_call": "Call {firstName}: {phone}",
        "cta_back": "Back to {firstName}'s Site"
      }
    }
  },
  "test-broker-agent": {
    "navigation": {
      "items": [
        {
          "label": "Home",
          "href": "#hero",
          "enabled": true
        },
        {
          "label": "Services",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "Team",
          "href": "#profiles",
          "enabled": true
        },
        {
          "label": "Contact",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "About",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Broker Direct Realty",
              "tagline": "Broker and mentor.",
              "body": "Diana Reyes leads Broker Direct Realty with hands-on expertise and a commitment to mentoring the next generation of agents.",
              "cta_text": "Get Started",
              "cta_link": "#contact_form"
            }
          },
          "stats": {
            "enabled": false,
            "data": {
              "items": []
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "Our Services",
              "subtitle": "Full-service brokerage for buyers and sellers.",
              "items": [
                {
                  "title": "Buyer Representation",
                  "description": "Expert guidance through every step of the home buying process."
                },
                {
                  "title": "Seller Services",
                  "description": "Strategic pricing, professional marketing, and skilled negotiation."
                }
              ]
            }
          },
          "steps": {
            "enabled": false,
            "data": {
              "steps": []
            }
          },
          "gallery": {
            "enabled": false,
            "data": {
              "items": []
            }
          },
          "testimonials": {
            "enabled": false,
            "data": {
              "items": []
            }
          },
          "profiles": {
            "enabled": true,
            "data": {
              "title": "Our Team",
              "subtitle": "Meet the agents of Broker Direct Realty.",
              "items": [
                {
                  "id": "agent-c",
                  "name": "Marcus Lee",
                  "title": "Associate Agent",
                  "phone": "(973) 555-0301",
                  "email": "marcus@brokerdirect.com"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "Contact Us",
              "subtitle": "Reach out to Broker Direct Realty."
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "About Broker Direct Realty",
              "bio": "Founded by Diana Reyes, Broker Direct Realty serves the Newark and Montclair communities with integrity and expertise.",
              "credentials": [
                "Licensed NJ Broker",
                "10+ Years Experience"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "We'll Be In Touch",
        "body": "A member of our team will contact you shortly.",
        "cta_back": "Back to Broker Direct Realty"
      }
    }
  },
  "test-brokerage": {
    "navigation": {
      "items": [
        {
          "label": "Home",
          "href": "#hero",
          "enabled": true
        },
        {
          "label": "Services",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "Team",
          "href": "#profiles",
          "enabled": true
        },
        {
          "label": "Portfolio",
          "href": "#gallery",
          "enabled": true
        },
        {
          "label": "Reviews",
          "href": "#testimonials",
          "enabled": true
        },
        {
          "label": "Contact",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "About",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Sterling & Associates Real Estate",
              "tagline": "Luxury real estate, personal service.",
              "body": "With over 30 years of experience in northern New Jersey's luxury market, Sterling & Associates delivers unmatched expertise and white-glove service for discerning buyers and sellers.",
              "cta_text": "Meet Our Team",
              "cta_link": "#profiles"
            }
          },
          "stats": {
            "enabled": true,
            "data": {
              "items": [
                {
                  "value": "500+",
                  "label": "Homes Sold"
                },
                {
                  "value": "30+",
                  "label": "Years Experience"
                },
                {
                  "value": "$2B+",
                  "label": "Total Sales Volume"
                },
                {
                  "value": "5.0",
                  "label": "Client Rating"
                }
              ]
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "Our Services",
              "subtitle": "Full-service luxury real estate for buyers and sellers.",
              "items": [
                {
                  "title": "Luxury Listings",
                  "description": "Expert marketing and staging for high-end properties in Summit, Short Hills, and Chatham."
                },
                {
                  "title": "Buyer Representation",
                  "description": "Exclusive access to off-market properties and new developments."
                },
                {
                  "title": "Market Analysis",
                  "description": "Data-driven pricing strategies backed by decades of local market knowledge."
                }
              ]
            }
          },
          "steps": {
            "enabled": false,
            "data": {
              "steps": []
            }
          },
          "gallery": {
            "enabled": true,
            "data": {
              "title": "Recent Sales",
              "subtitle": "A selection of properties sold by our team.",
              "items": [
                {
                  "address": "100 Summit Ave",
                  "city": "Summit",
                  "state": "NJ",
                  "price": "$2,100,000"
                },
                {
                  "address": "55 Old Short Hills Rd",
                  "city": "Short Hills",
                  "state": "NJ",
                  "price": "$1,850,000"
                }
              ]
            }
          },
          "testimonials": {
            "enabled": true,
            "data": {
              "title": "Client Reviews",
              "subtitle": "What our clients say about working with Sterling & Associates.",
              "items": [
                {
                  "text": "Victoria and her team made selling our home a seamless experience. Their market knowledge is unmatched.",
                  "reviewer": "The Hendersons",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "James found us the perfect property in Summit. Professional, knowledgeable, and always available.",
                  "reviewer": "Mark & Lisa P.",
                  "rating": 5,
                  "source": "Zillow"
                }
              ]
            }
          },
          "profiles": {
            "enabled": true,
            "data": {
              "title": "Meet Our Team",
              "subtitle": "Experienced agents dedicated to your success.",
              "items": [
                {
                  "id": "agent-a",
                  "name": "James Whitfield",
                  "title": "Senior Associate",
                  "phone": "(908) 555-0101",
                  "email": "james@sterling.com"
                },
                {
                  "id": "agent-b",
                  "name": "Sarah Chen",
                  "title": "Luxury Specialist",
                  "phone": "(908) 555-0102",
                  "email": "sarah@sterling.com"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "Get In Touch",
              "subtitle": "Contact Sterling & Associates for a complimentary consultation."
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "About Sterling & Associates",
              "bio": "Founded by Victoria Sterling, Sterling & Associates has been serving northern New Jersey's luxury real estate market for over 30 years. Our team of experienced agents brings deep local knowledge and a commitment to exceptional client service.",
              "credentials": [
                "30+ Years Experience",
                "500+ Homes Sold",
                "$2B+ Total Volume"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "We'll Be In Touch Shortly",
        "body": "A member of the Sterling & Associates team will reach out to you soon.",
        "cta_back": "Back to Sterling & Associates"
      }
    }
  },
  "test-emerald": {
    "navigation": {
      "items": [
        {
          "label": "Why Choose Me",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "How It Works",
          "href": "#steps",
          "enabled": true
        },
        {
          "label": "Recent Sales",
          "href": "#gallery",
          "enabled": true
        },
        {
          "label": "Testimonials",
          "href": "#testimonials",
          "enabled": true
        },
        {
          "label": "Free Home Value",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "About",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Sell Your Home for Top Dollar",
              "highlight_word": "Top Dollar",
              "tagline": "Your Home. Your Future. My Priority.",
              "body": "I'm Patricia Collins, a NJ State Licensed REALTOR® with Evergreen Homes Realty. With 15 years of experience and over 200 homes sold, I know what it takes to get you the best price. Whether you're upsizing, downsizing, or making your first move — I'm here to guide you every step of the way.",
              "cta_text": "Get Your Free Home Value Report",
              "cta_link": "#cma-form"
            }
          },
          "stats": {
            "enabled": true,
            "data": {
              "items": [
                {
                  "value": "200+",
                  "label": "Homes Sold"
                },
                {
                  "value": "4.9 ★",
                  "label": "Google Rating (38 Reviews)"
                },
                {
                  "value": "15+",
                  "label": "Years Experience"
                },
                {
                  "value": "$350K–$1.2M",
                  "label": "Sale Price Range"
                }
              ]
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "Why Work With Me",
              "subtitle": "Full-service real estate from first call to closing day.",
              "items": [
                {
                  "title": "Free Home Valuation",
                  "description": "Get a professional Comparative Market Analysis showing exactly what your home is worth in today's market — completely free."
                },
                {
                  "title": "Professional Photography & Staging",
                  "description": "Every listing gets magazine-quality photos and virtual staging to make buyers fall in love online."
                },
                {
                  "title": "Strategic Pricing",
                  "description": "Data-backed pricing strategies that attract competitive offers and avoid sitting on the market."
                },
                {
                  "title": "Maximum Exposure",
                  "description": "MLS, Zillow, Realtor.com, social media ads, and targeted email campaigns to reach serious buyers fast."
                },
                {
                  "title": "Buyer Representation",
                  "description": "Looking to buy? I'll help you find the right home, negotiate the best deal, and navigate inspections and closing."
                },
                {
                  "title": "Relocation Assistance",
                  "description": "Moving in or out of the area? I coordinate with relocation specialists to make your transition seamless."
                }
              ]
            }
          },
          "steps": {
            "enabled": true,
            "data": {
              "title": "How It Works",
              "subtitle": "Three simple steps to get started.",
              "steps": [
                {
                  "number": 1,
                  "title": "Submit Your Info",
                  "description": "Fill out the quick form below with your property details. Takes less than 2 minutes."
                },
                {
                  "number": 2,
                  "title": "Get Your Home Value Report",
                  "description": "I'll send you a personalized report showing what your home is worth based on recent comparable sales in your area."
                },
                {
                  "number": 3,
                  "title": "Meet & Plan",
                  "description": "We'll meet in person or virtually to discuss your goals and create a customized strategy."
                }
              ]
            }
          },
          "gallery": {
            "enabled": true,
            "data": {
              "title": "Recently Sold by Patricia",
              "subtitle": "Real results for real families across Central New Jersey.",
              "items": [
                {
                  "address": "42 Oak Tree Rd",
                  "city": "Edison",
                  "state": "NJ",
                  "price": "$575,000",
                  "image_url": "/agents/test-emerald/sold/42-oak-tree.jpg"
                },
                {
                  "address": "18 Maple Ave",
                  "city": "Woodbridge",
                  "state": "NJ",
                  "price": "$485,000",
                  "image_url": "/agents/test-emerald/sold/18-maple-ave.jpg"
                },
                {
                  "address": "305 Park Ave",
                  "city": "Scotch Plains",
                  "state": "NJ",
                  "price": "$720,000",
                  "image_url": "/agents/test-emerald/sold/305-park-ave.jpg"
                },
                {
                  "address": "88 Elm St",
                  "city": "Westfield",
                  "state": "NJ",
                  "price": "$890,000",
                  "image_url": "/agents/test-emerald/sold/88-elm-st.jpg"
                }
              ]
            }
          },
          "testimonials": {
            "enabled": true,
            "data": {
              "title": "What My Clients Say",
              "subtitle": "Real reviews from happy homeowners.",
              "items": [
                {
                  "text": "Patricia sold our home in just 5 days for over asking price! She handled everything from staging to closing with incredible professionalism. Cannot recommend her enough.",
                  "reviewer": "The Martinez Family",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "As first-time buyers, we were nervous about the process. Patricia made it feel easy and exciting. She found us the perfect home in our budget and negotiated a great deal.",
                  "reviewer": "Mike & Sarah T.",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "We've worked with Patricia on three transactions now — buying our first home, selling it, and buying our forever home. She's our realtor for life!",
                  "reviewer": "Jennifer K.",
                  "rating": 5,
                  "source": "Zillow"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "What's Your Home Worth?",
              "subtitle": "Get a free, no-obligation Home Value Report in minutes.",
              "description": "Enter your property details below and I'll send you a personalized market analysis based on recent sales in your neighborhood. **100% free, no obligation.**"
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "About Patricia",
              "bio": [
                "I'm Patricia Collins — a lifelong New Jersey resident, NJ State Licensed REALTOR®, and proud member of Evergreen Homes Realty. For over 15 years, I've helped families across Middlesex, Union, and Somerset Counties buy and sell homes with confidence.",
                "With more than 200 successful transactions, I bring deep market knowledge and a personal touch to every deal. My clients know they can count on me for honest advice, clear communication, and results that exceed expectations.",
                "When I'm not showing homes, you'll find me volunteering at the local food bank, cheering on my kids' soccer teams, or exploring the Jersey Shore."
              ],
              "credentials": [
                "NJ State Licensed",
                "200+ Homes Sold",
                "4.9 ★ Google",
                "NJ REALTORS® Member"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "Your Home Value Report Is On Its Way!",
        "body": "{firstName} will send your personalized report to your email shortly.",
        "disclaimer": "This report is a Comparative Market Analysis (CMA) and is not an appraisal.",
        "cta_call": "Call {firstName}: {phone}",
        "cta_back": "Back to {firstName}'s Site"
      }
    }
  },
  "test-modern": {
    "navigation": {
      "items": [
        {
          "label": "Services",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "Process",
          "href": "#steps",
          "enabled": true
        },
        {
          "label": "Sales",
          "href": "#gallery",
          "enabled": true
        },
        {
          "label": "Reviews",
          "href": "#testimonials",
          "enabled": true
        },
        {
          "label": "Get Started",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "About",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Find Your Perfect NYC Home",
              "tagline": "City Living. Simplified.",
              "body": "I'm Alex Rivera — a licensed NYC real estate professional specializing in Manhattan condos, Brooklyn brownstones, and Queens co-ops. With deep neighborhood knowledge and a data-first approach, I help clients make confident decisions in the city's fastest-moving market.",
              "cta_text": "Get Your Free Market Analysis",
              "cta_link": "#cma-form"
            }
          },
          "stats": {
            "enabled": true,
            "data": {
              "items": [
                {
                  "value": "150+",
                  "label": "Transactions Closed"
                },
                {
                  "value": "4.8 ★",
                  "label": "Google Rating"
                },
                {
                  "value": "8+",
                  "label": "Years in NYC"
                },
                {
                  "value": "$45M+",
                  "label": "Total Sales Volume"
                }
              ]
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "What I Offer",
              "subtitle": "Full-service real estate for the NYC market.",
              "items": [
                {
                  "title": "Market Analysis",
                  "description": "Data-driven pricing using recent comparable sales, market trends, and neighborhood-level analytics."
                },
                {
                  "title": "Expert Negotiation",
                  "description": "Experienced deal-making in competitive bidding situations — I've won offers in 10+ bid wars this year alone."
                },
                {
                  "title": "Full-Service Closing",
                  "description": "Coordinated from accepted offer through keys in hand — attorneys, inspections, and board packages handled."
                },
                {
                  "title": "Buyer Representation",
                  "description": "Exclusive buyer agency with access to off-market listings and new developments before public launch."
                },
                {
                  "title": "Investment Advisory",
                  "description": "ROI analysis, rental yield projections, and portfolio strategy for real estate investors."
                }
              ]
            }
          },
          "steps": {
            "enabled": true,
            "data": {
              "title": "How It Works",
              "subtitle": "Three steps to your next move.",
              "steps": [
                {
                  "number": 1,
                  "title": "Tell Me What You Need",
                  "description": "Fill out the form with your details — buying, selling, or just exploring."
                },
                {
                  "number": 2,
                  "title": "Get Your Report",
                  "description": "Receive a personalized market analysis with comparable sales, pricing trends, and my professional recommendation."
                },
                {
                  "number": 3,
                  "title": "Let's Meet",
                  "description": "Schedule a walkthrough, virtual tour, or strategy session — whatever works for you."
                }
              ]
            }
          },
          "gallery": {
            "enabled": true,
            "data": {
              "title": "Recent Sales",
              "subtitle": "Closed deals across New York City's most competitive neighborhoods.",
              "items": [
                {
                  "address": "350 Fifth Ave, Unit 42B",
                  "city": "Manhattan",
                  "state": "NY",
                  "price": "$1,250,000",
                  "image_url": "/agents/test-modern/sold/350-fifth-ave.jpg"
                },
                {
                  "address": "200 Park Ave, Unit 18A",
                  "city": "Manhattan",
                  "state": "NY",
                  "price": "$890,000",
                  "image_url": "/agents/test-modern/sold/200-park-ave.jpg"
                },
                {
                  "address": "88 Greenpoint Ave",
                  "city": "Brooklyn",
                  "state": "NY",
                  "price": "$725,000",
                  "image_url": "/agents/test-modern/sold/88-greenpoint.jpg"
                },
                {
                  "address": "45 Court St, Unit 6F",
                  "city": "Brooklyn",
                  "state": "NY",
                  "price": "$680,000",
                  "image_url": "/agents/test-modern/sold/45-court-st.jpg"
                }
              ]
            }
          },
          "testimonials": {
            "enabled": true,
            "data": {
              "title": "Client Reviews",
              "subtitle": "What past clients say about working with me.",
              "items": [
                {
                  "text": "Alex found us the perfect condo in record time. Incredibly responsive and knows every neighborhood inside out. We never felt rushed or pressured.",
                  "reviewer": "Sarah M.",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "Best experience buying in NYC. Alex's data-driven approach gave us confidence in a crazy market. Closed $30K under asking.",
                  "reviewer": "James & Priya",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "We were relocating from Chicago and Alex made the entire process seamless. Virtual tours, neighborhood guides, school info — he covered everything.",
                  "reviewer": "The Chen Family",
                  "rating": 5,
                  "source": "Zillow"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "What's Your Property Worth?",
              "subtitle": "Get a free NYC market analysis in minutes.",
              "description": "Enter your address below and I'll send you a detailed market analysis with comparable sales, price trends, and my professional valuation. **100% free, no strings.**"
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "About Alex",
              "bio": [
                "I'm Alex Rivera — a licensed real estate salesperson with Metro Realty Group, specializing in NYC residential real estate. From Manhattan condos to Brooklyn brownstones, I've closed over 150 transactions totaling $45M+ in sales volume.",
                "My approach is data-first: I use market analytics, neighborhood trends, and pricing models to help clients make smart decisions. Whether you're a first-time buyer, seasoned investor, or ready to sell, I bring the same level of research and dedication to every deal.",
                "Born in Queens, raised in the Bronx, and living in Brooklyn — I know this city inside and out."
              ],
              "credentials": [
                "Licensed NY Salesperson",
                "Top 10% NYC Volume",
                "150+ Transactions",
                "Fluent in Portuguese"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "Your Market Analysis Is Being Prepared",
        "body": "{firstName} will send your personalized NYC market report to your email shortly.",
        "disclaimer": "This report is a Comparative Market Analysis (CMA) and is not an appraisal.",
        "cta_call": "Call {firstName}: {phone}",
        "cta_back": "Back to {firstName}'s Site"
      }
    }
  },
  "test-warm": {
    "navigation": {
      "items": [
        {
          "label": "Services",
          "href": "#features",
          "enabled": true
        },
        {
          "label": "Process",
          "href": "#steps",
          "enabled": true
        },
        {
          "label": "Sold Homes",
          "href": "#gallery",
          "enabled": true
        },
        {
          "label": "Reviews",
          "href": "#testimonials",
          "enabled": true
        },
        {
          "label": "Free Home Value",
          "href": "#contact_form",
          "enabled": true
        },
        {
          "label": "Meet Maria",
          "href": "#about",
          "enabled": true
        }
      ]
    },
    "pages": {
      "home": {
        "sections": {
          "hero": {
            "enabled": true,
            "data": {
              "headline": "Buy or Sell in the Hill Country",
              "tagline": "Your Neighbor. Your REALTOR®.",
              "body": "I'm Maria Santiago, born and raised in Central Texas. Whether you're selling your family home or searching for your next chapter, I bring local expertise and genuine care to every transaction. With over 12 years in the business and 75+ homes sold, I know this market — and I know how to get results.",
              "cta_text": "Get Your Free Home Value",
              "cta_link": "#cma-form"
            }
          },
          "stats": {
            "enabled": true,
            "data": {
              "items": [
                {
                  "value": "75+",
                  "label": "Homes Sold"
                },
                {
                  "value": "4.9 ★",
                  "label": "Google Rating (27 Reviews)"
                },
                {
                  "value": "12+",
                  "label": "Years Experience"
                },
                {
                  "value": "$250K–$800K",
                  "label": "Sale Price Range"
                }
              ]
            }
          },
          "features": {
            "enabled": true,
            "data": {
              "title": "How I Help",
              "subtitle": "Full-service real estate for buyers and sellers.",
              "items": [
                {
                  "title": "Free Home Valuation",
                  "description": "Get a professional market analysis of your home's current value — completely free, no strings attached."
                },
                {
                  "title": "Buyer Representation",
                  "description": "I'll find homes that fit your budget and lifestyle, schedule tours, and negotiate the best deal on your behalf."
                },
                {
                  "title": "Listing & Marketing",
                  "description": "Professional photos, MLS listing, social media exposure, open houses, and targeted digital ads to attract serious buyers."
                },
                {
                  "title": "Relocation Support",
                  "description": "Moving to Central Texas? I'll help you find the right neighborhood, schools, and community for your family."
                },
                {
                  "title": "Bilingual Service",
                  "description": "Fluent in English and Spanish — every client gets clear communication and personal attention in their preferred language."
                }
              ]
            }
          },
          "steps": {
            "enabled": true,
            "data": {
              "title": "Getting Started Is Easy",
              "subtitle": "Three steps to your next move.",
              "steps": [
                {
                  "number": 1,
                  "title": "Reach Out",
                  "description": "Fill out the form below or give me a call. I respond within the hour."
                },
                {
                  "number": 2,
                  "title": "Get Your Plan",
                  "description": "Selling? I'll send you a free Home Value Report. Buying? I'll learn about your needs and start searching."
                },
                {
                  "number": 3,
                  "title": "Make Your Move",
                  "description": "Buy or sell with confidence — I'll be with you every step, from first showing to closing day."
                }
              ]
            }
          },
          "gallery": {
            "enabled": true,
            "data": {
              "title": "Homes Sold by Maria",
              "subtitle": "Helping families find their place in Central Texas.",
              "items": [
                {
                  "address": "1100 Congress Ave",
                  "city": "Austin",
                  "state": "TX",
                  "price": "$485,000",
                  "image_url": "/agents/test-warm/sold/1100-congress.jpg"
                },
                {
                  "address": "450 Barton Springs Rd",
                  "city": "Austin",
                  "state": "TX",
                  "price": "$620,000",
                  "image_url": "/agents/test-warm/sold/450-barton-springs.jpg"
                },
                {
                  "address": "220 Round Rock Ave",
                  "city": "Round Rock",
                  "state": "TX",
                  "price": "$375,000",
                  "image_url": "/agents/test-warm/sold/220-round-rock.jpg"
                },
                {
                  "address": "85 Cedar Park Blvd",
                  "city": "Cedar Park",
                  "state": "TX",
                  "price": "$410,000",
                  "image_url": "/agents/test-warm/sold/85-cedar-park.jpg"
                }
              ]
            }
          },
          "testimonials": {
            "enabled": true,
            "data": {
              "title": "What Clients Say",
              "subtitle": "Real reviews from families I've helped.",
              "items": [
                {
                  "text": "Maria made selling our home so easy. She handled everything and kept us informed the whole time. We got multiple offers in the first weekend!",
                  "reviewer": "The Johnson Family",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "We were first-time buyers and Maria walked us through every step. She found us the perfect home in Round Rock and negotiated $15K off the asking price.",
                  "reviewer": "David & Lisa",
                  "rating": 5,
                  "source": "Google"
                },
                {
                  "text": "Maria helped my parents sell their home of 30 years. She was patient, respectful, and got them a great price. We couldn't have asked for a better experience.",
                  "reviewer": "Carlos R.",
                  "rating": 5,
                  "source": "Zillow"
                }
              ]
            }
          },
          "contact_form": {
            "enabled": true,
            "data": {
              "title": "What's Your Home Worth?",
              "subtitle": "Get a free, no-obligation home value report.",
              "description": "Enter your address below and I'll send you a personalized market analysis based on recent sales in your neighborhood. **100% free, no obligation.**"
            }
          },
          "about": {
            "enabled": true,
            "data": {
              "title": "Meet Maria",
              "bio": [
                "I'm Maria Santiago — a lifelong Central Texan, proud mom, and your neighbor. I've been helping families buy and sell homes in the Austin area for over 12 years, with 75+ successful transactions under my belt.",
                "I believe real estate is about people, not just properties. Every client gets my personal attention, honest advice, and the kind of service I'd want for my own family. Whether you're buying your first home or downsizing after the kids move out, I'm here to help.",
                "When I'm not showing homes, you'll find me at my kids' baseball games, volunteering at our church, or exploring new restaurants on South Congress."
              ],
              "credentials": [
                "Licensed TX REALTOR®",
                "75+ Homes Sold",
                "Bilingual: English & Spanish",
                "Austin Board of REALTORS® Member"
              ]
            }
          },
          "city_pages": {
            "enabled": false,
            "data": {
              "cities": []
            }
          }
        }
      },
      "thank_you": {
        "heading": "Thank You!",
        "subheading": "Your Home Value Report Is On Its Way!",
        "body": "{firstName} will send your personalized report to your email shortly.",
        "disclaimer": "This report is a Comparative Market Analysis (CMA) and is not an appraisal.",
        "cta_call": "Call {firstName}: {phone}",
        "cta_back": "Back to {firstName}'s Site"
      }
    }
  }
} as unknown as Record<string, ContentConfig>;

export const agentConfigs: Record<string, Record<string, AgentConfig>> = {
  "test-broker-agent": {
    "agent-c": {
      "id": "agent-c",
      "name": "Marcus Lee",
      "title": "Associate Agent",
      "phone": "(973) 555-0301",
      "email": "marcus@brokerdirect.com"
    }
  },
  "test-brokerage": {
    "agent-a": {
      "id": "agent-a",
      "name": "James Whitfield",
      "title": "Senior Associate",
      "phone": "(908) 555-0101",
      "email": "james@sterling.com",
      "headshot_url": "/agents/test-brokerage/agents/james-whitfield/headshot.jpg",
      "license_number": "NJ-2024-67890",
      "languages": [
        "English"
      ],
      "tagline": "Your land expert.",
      "credentials": [
        "REALTOR®",
        "CRS",
        "ABR"
      ]
    },
    "agent-b": {
      "id": "agent-b",
      "name": "Sarah Chen",
      "title": "Luxury Specialist",
      "phone": "(908) 555-0102",
      "email": "sarah@sterling.com",
      "headshot_url": "/agents/test-brokerage/agents/sarah-chen/headshot.jpg",
      "license_number": "NJ-2024-11111",
      "languages": [
        "English",
        "Mandarin"
      ],
      "tagline": "Connecting you with the perfect home.",
      "credentials": [
        "REALTOR®",
        "ABR"
      ]
    }
  }
} as unknown as Record<string, Record<string, AgentConfig>>;

export const agentContent: Record<string, Record<string, ContentConfig>> = {
  "test-broker-agent": {
    "agent-c": {
      "pages": {
        "home": {
          "sections": {
            "hero": {
              "enabled": true,
              "data": {
                "headline": "Marcus Lee — Associate Agent",
                "tagline": "Dedicated to your success.",
                "cta_text": "Work With Marcus",
                "cta_link": "#contact_form"
              }
            },
            "stats": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "features": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "steps": {
              "enabled": false,
              "data": {
                "steps": []
              }
            },
            "gallery": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "testimonials": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "profiles": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "contact_form": {
              "enabled": true,
              "data": {
                "title": "Work With Marcus",
                "subtitle": "Let's find your next home."
              }
            },
            "about": {
              "enabled": true,
              "data": {
                "bio": "Marcus Lee is an associate agent at Broker Direct Realty, serving the Newark and Montclair communities."
              }
            },
            "city_pages": {
              "enabled": false,
              "data": {
                "cities": []
              }
            }
          }
        }
      }
    }
  },
  "test-brokerage": {
    "agent-a": {
      "pages": {
        "home": {
          "sections": {
            "hero": {
              "enabled": true,
              "data": {
                "headline": "James Whitfield — Senior Associate",
                "tagline": "Your land expert.",
                "cta_text": "Work With James",
                "cta_link": "#contact_form"
              }
            },
            "stats": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "features": {
              "enabled": true,
              "data": {
                "title": "My Specialties",
                "items": [
                  {
                    "title": "Land Sales",
                    "description": "Expert in vacant land and development parcels."
                  }
                ]
              }
            },
            "steps": {
              "enabled": false,
              "data": {
                "steps": []
              }
            },
            "gallery": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "testimonials": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "profiles": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "contact_form": {
              "enabled": true,
              "data": {
                "title": "Work With James",
                "subtitle": "Let's find your next property."
              }
            },
            "about": {
              "enabled": true,
              "data": {
                "bio": "James specializes in vacant land across northern NJ.",
                "credentials": [
                  "REALTOR®"
                ]
              }
            },
            "city_pages": {
              "enabled": false,
              "data": {
                "cities": []
              }
            }
          }
        }
      }
    },
    "agent-b": {
      "pages": {
        "home": {
          "sections": {
            "hero": {
              "enabled": true,
              "data": {
                "headline": "Sarah Chen — Luxury Specialist",
                "tagline": "Connecting you with the perfect home.",
                "cta_text": "Work With Sarah",
                "cta_link": "#contact_form"
              }
            },
            "stats": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "features": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "steps": {
              "enabled": false,
              "data": {
                "steps": []
              }
            },
            "gallery": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "testimonials": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "profiles": {
              "enabled": false,
              "data": {
                "items": []
              }
            },
            "contact_form": {
              "enabled": true,
              "data": {
                "title": "Work With Sarah",
                "subtitle": "Let me find your dream home."
              }
            },
            "about": {
              "enabled": true,
              "data": {
                "bio": "Sarah Chen brings luxury property expertise and fluent Mandarin.",
                "credentials": [
                  "REALTOR®",
                  "ABR"
                ]
              }
            },
            "city_pages": {
              "enabled": false,
              "data": {
                "cities": []
              }
            }
          }
        }
      }
    }
  }
} as unknown as Record<string, Record<string, ContentConfig>>;

export const legalContent: Record<string, Record<string, { above?: string; below?: string }>> = {};

export const customDomains: Record<string, string> = {};

export const accountHandles: Set<string> = new Set(["jenise-buckalew","test-broker-agent","test-brokerage","test-emerald","test-modern","test-warm"]);
