global using Xunit;
global using Moq;
global using FluentAssertions;

// Domain namespaces
global using RealEstateStar.Domain.Shared.Models;
global using RealEstateStar.Domain.Shared.Markdown;
global using RealEstateStar.Domain.Leads.Models;
global using RealEstateStar.Domain.Leads.Markdown;
global using RealEstateStar.Domain.Leads;
global using RealEstateStar.Domain.Cma.Models;
global using RealEstateStar.Domain.Cma.Interfaces;
global using RealEstateStar.Domain.Cma.Services;
global using RealEstateStar.Domain.HomeSearch.Markdown;
global using RealEstateStar.Domain.WhatsApp.Models;
global using RealEstateStar.Domain.WhatsApp;
global using RealEstateStar.Domain.Onboarding.Models;
global using RealEstateStar.Domain.Onboarding.Services;
global using RealEstateStar.Domain.Onboarding;
