import createClient from "openapi-fetch";
import { createCorrelationId } from "@real-estate-star/domain";
// Types will be generated by the `generate` script
// import type { paths } from "./generated/types";

export function createApiClient(baseUrl: string, apiKey?: string) {
  return createClient({
    baseUrl,
    headers: {
      "X-Correlation-ID": createCorrelationId(),
      ...(apiKey ? { "X-API-Key": apiKey } : undefined),
    },
  });
}
