import createClient from "openapi-fetch";
// Types will be generated by the `generate` script
// import type { paths } from "./generated/types";

export function createApiClient(baseUrl: string, apiKey?: string) {
  return createClient({
    baseUrl,
    headers: apiKey ? { "X-API-Key": apiKey } : undefined,
  });
}
