export { TestimonialsGrid } from "./TestimonialsGrid";
export { TestimonialsClean } from "./TestimonialsClean";
export { TestimonialsBubble } from "./TestimonialsBubble";
export { TestimonialsMinimal } from "./TestimonialsMinimal";
export { TestimonialsStack } from "./TestimonialsStack";
export { TestimonialsHeart } from "./TestimonialsHeart";
export { TestimonialsQuote } from "./TestimonialsQuote";
export { TestimonialsBeach } from "./TestimonialsBeach";
export { TestimonialsCorporate } from "./TestimonialsCorporate";
