export { AboutSplit } from "./AboutSplit";
export { AboutMinimal } from "./AboutMinimal";
export { AboutCard } from "./AboutCard";
export { AboutEditorial } from "./AboutEditorial";
export { AboutCompact } from "./AboutCompact";
export { AboutWarm } from "./AboutWarm";
export { AboutGrace } from "./AboutGrace";
export { AboutCoastal } from "./AboutCoastal";
export { AboutProfessional } from "./AboutProfessional";
